services:

  vectradb:
    build: 
      context: ./src
    ports:
      - "50051:50051"
    networks:
      - vectra-network



  api-gateway:
    build:
      context: ./src
      dockerfile: gateway.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - vectradb
    networks:
      - vectra-network

  frontend-ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api-gateway
    networks:
      - vectra-network



networks:
  vectra-network:
    driver: bridge